# Generated by Django 5.2.14 on 2026-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2026-06-10'),
            preserve_default=False,
        ),
    ]
